### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by spirali** [spirali/orco#1]
* [x] Finish collection API (.compute, .remove, ..., .get)
* [x] collection.clean()
* [x] command line API
* [ ] ~~Obj API (or just use dict?)~~
* [x] Generating cartesian product for Obj (or dict?) Builder(graph=[..], model=[..]) = [Obj<graph=.. model=..>, .... ]
* [ ] Simple LocalExecutor that respects dependencies and shows some progress (tqdm)
* [ ] Queries API for getting results from DB
* [ ] Export a collection into Pandas frame
* [ ] Dask Executor
* [ ] "repeat" API
* [ ] Iterative collection API
* [x] Saving information about computation (computation duration, etc)
* [x] Prediction of a computation
* [ ] fail-safe mode for executor
* [x] Possibility to return JSON like object with refs from dep_fn
* [x] Runtime context manager

**Comment by Kobzol** [comment]
- [x] non-blocking serve
- [x] invalidation of collections (or "temporary" collections)
- [x] debug mode (log more information about computation to debug/trace)
- [x] get computed results without new computation 
- [ ] hierarchical config exploration in browser
- [x] config metadata (timeout for computation)
